# https://swagger.io/specification/
# https://commonmark.org/help/
# https://yaml.org/
# https://yaml-multiline.info/
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Dummy endpoints for testing"
  description: "A sample API containing some dummy endpoints for testing"
  termsOfService: "<termsOfService URL>"
  contact:
    name: "API support"
    url: "<contact information URL>"
    email: "support@dummy.fake"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
servers:
  - url: "<server URL where API is expossed>"
    description: "dummy description of the API expossed on this server"
    variables:
      dummyVariable00:
        default: "0"
        description: The description 1
        enum:
          - "0"
          - "1"
          - "2"
      dummyVariable01:
        default: "v1"
        description: The description 2
        enum:
          - "v1"
          - "v2"
paths:
  /dummy:
    get:
      responses:
        200:
          description: "A dummy GET response"
          content:
            application/json:
              examples:
                dummy:
                  value:
                    status: "GET ok"
    post:
      responses:
        201:
          description: "A dummy POST response"
          content:
            application/json:
              examples:
                dummy:
                  value:
                    status: "POST ok"
    put:
      responses:
        200:
          description: "A dummy PUT response"
          content:
            application/json:
              examples:
                dummy:
                  value:
                    status: "PUT ok"
    patch:
      responses:
        200:
          description: "A dummy PATCH response"
          content:
            application/json:
              examples:
                dummy:
                  value:
                    status: "PATCH ok"
    delete:
      responses:
        200:
          description: "A dummy DELETE response"
          content:
            application/json:
              examples:
                dummy:
                  value:
                    status: "DELETE ok"
