# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
  express-gateway-plugin-openapi3-mock-server:
    definitionFile: './config/mock-openapi3.yml'
    package: '../express-gateway-plugin-openapi3-mock-server/manifest.js'
  express-gateway-plugin-errors:

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
